import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import {Header} from "@/components/header";
import {Inter} from "next/font/google";
import {Section1} from "@/components/section-1";
import {Section2} from "@/components/section-2";
import {Developer} from "@/components/developer";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Header/>
        <Section1/>
        <Section2/>
        <Developer/>
      </main>
    </>
  )
}
